Error: Cannot find module 'fs/promises' Fixes issue #22
Updated module imports

*  src/deploy.js
Updated fs promises import for Node 12+

* src/index.js
Removed unused promises import

* src/minty.js
Updated fs promises import for Node12+